stages:
  - build

# Docker version on host system
image: docker:20.10.21

variables:
  DOCKER_DRIVER: overlay2

build:
  stage: build
  tags:
    - docker
  before_script:
    - apk add --no-cache make git
    # Load building parameters
    - set -a; source build-docker/build.env; set +a
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    - echo "Triggered by $CI_PIPELINE_SOURCE"
    - cd build-docker
    - make rebuild push JAVA_VERSION=$JAVA_VERSION UBUNTU_VERSION=$UBUNTU_VERSION
  only:
    - branches
    - triggers
