stages:
  - build

image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

build:
  stage: build
  tags:
    - docker
  before_script:
    - apk add make
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    - echo "Triggered by $CI_PIPELINE_SOURCE"
    - cd build-docker
    - make rebuild push
  only:
    - branches
    - triggers
